### ISSUE TITLE
Issues "status" not migrated to Github

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rolly32/rolly#110] opened 2015-07-31 16:58 UTC
```
We migrated our thousands of issues to Github: 
https://github.com/hssm/test_ad_issues/issues

Unfortunately, all issues lack the "status" information.

Status is vital information, it indicates whether an issue is "New" (pending 
investigation) or "Accepted" (the issue was reproduced and a developer must fix 
it).
```

Original issue reported on code.google.com by `nicolas.raoul@gmail.com` on 28 Jul 2015 at 6:50

**Comment by rolly32** [comment] 2015-07-31 18:24
We migrated our thousands of issues to Github: 
https://github.com/hssm/test_ad_issues/issues

Unfortunately, all issues lack the "status" information.

Status is vital information, it indicates whether an issue is "New" (pending 
investigation) or "Accepted" (the issue was reproduced and a developer must fix 
it).
Original issue reported on code.google.com by nicolas.raoul@gmail.com on 28 Jul 2015 at 6:50

**Comment by rolly32** [comment] 2015-07-31 18:25
Could you explain what behavior you would like to see instead? It looks like 
the status information is present, but probably not in the format that you want.

https://github.com/hssm/test_ad_issues/issues/2673
"- *Status changed*: WaitingForFeedback"

Would you want the status displayed on every issue update? Or status applied as 
a label to the issue?
Original comment by chrsm...@google.com on 28 Jul 2015 at 2:35

**Comment by rolly32** [comment] 2015-07-31 18:29
Thanks for the fast reply!

The status should be a label, for instance "New" or "Accepted" or 
"WaitingForFeedback".
That would allow a developer to filter and concentrate only on the issues that 
have been marked as "Accepted" by the Triage people.
Original comment by nicolas.raoul@gmail.com on 28 Jul 2015 at 3:51

**Closed as completed by rolly32** 2015-07-31 18:29 UTC
Labels: Priority-Medium, auto-migrated, Type-Defect
